### ISSUE TITLE
Typer API?

### ISSUE THREAD

**Issue by CodeFix1027** [CodeFix1027/SMD#17]
We are making our own command-line argument parser. What if we use the Typer API to parse arguments and save time? It also makes the program more open to integrations and easier to read (I hope so).

[Typer -- Typer, build great CLIs. Easy to code. Based on Python type hints.](https://typer.tiangolo.com/)

**Comment by Chris1320** [comment]
Should we rewrite the program?

**Comment by CodeFix1027** [comment]
I think so.

Let's just create a new branch.

**Comment by Chris1320** [comment]
Oh, that was fast. Anyways, sure

**Comment by CodeFix1027** [comment]
We are now using Typer since commit ea88a17.
